name:                eva
version:             0.1.0.0
github:              "hei411/eva"
license:             BSD3
author:              "Hei Li"
maintainer:          "Hei.Li@cl.cam.ac.uk"
copyright:           "2021 Li Kwing Hei"

extra-source-files:
- README.md
- ChangeLog.md
- TODO.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hei411/eva/blob/main/README.md>

dependencies:
- base >= 4.7 && < 5
- parsec

library:
  source-dirs: src
  ghc-options:
  - -fwarn-incomplete-patterns 
  - -fwarn-incomplete-uni-patterns
  - -Werror
executables:
  eva:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eva
    

tests:
  eva-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eva
